### ISSUE TITLE
Ошибки с аксессорами в паттерне прокси (не компилируется)

### ISSUE THREAD

**Issue by ed-asriyan** [Panda-Lewandowski/Design-Patterns#4]
Можно исправить, например, так

```C++
class Image {
	protected:
		int myId;
		Image();
		~Image();
		virtual void draw() = 0;
};

class RealImage : public Image {
	public:
		RealImage(int i) { myId = i; }

		void draw() { cout << " drawing image " << myId << '\n'; }
};

class ProxyImage : public Image {
		RealImage* realImage;
		static int next;
	public:
		ProxyImage() {
			myId = next++;
			realImage = 0;
		}

		void draw() {
			if (!realImage) {
				realImage = new RealImage(myId);
			}
			realImage->draw();
		}
};

int ProxyImage::next = 1;
```
**UPD:** еще желательно определить конструктор/деструктор `Image` (.cpp я не нашёл):
```C++
		Image() = default;
		~Image() = default;
```

**Comment by Panda-Lewandowski** [comment]
А в чем там ошибка?

**Comment by ed-asriyan** [comment]
1. В `RealImage` ты обращаешься к приватному полю `Image::myId`, [тык](https://github.com/Panda-Lewandowski/Design-Patterns/blob/master/proxy.hpp#L14);
2. В `ProxyImage` оращаешься к приватному конструктору `RealImage`, [тык](https://github.com/Panda-Lewandowski/Design-Patterns/blob/master/proxy.hpp#L32);
3. В `ProxyImage` ты обращаешься к приватному полю `Image::myId`, [тык](https://github.com/Panda-Lewandowski/Design-Patterns/blob/master/proxy.hpp#L25);
